org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
java_version=21

fabric_loader_version=0.19.2
fabric_api_version=0.116.12+1.21.1
neo_version=21.1.228
neo_version_range=[21.1.0,)
loader_version_range=[4,)
puffish_skills_version=0.18.3
puffish_skills_fabric_file=8547653
puffish_skills_neoforge_file=8547654
rinlib_fabric_version=1.0.0+1.21.1-fabric
rinlib_neoforge_version=1.0.0+1.21.1-neoforge
rinlib_runtime_version=1.0.0+1.21.1
rinlib_neoforge_runtime_version=1.0.0

mod_id=skill_respec_pill
mod_name=Skill Respec Pill
mod_license=GPL-3.0
mod_version=1.0.3
mod_group_id=dev.rinchan
mod_authors=RinChan
mod_description=\u4e3a Puffish Skills \u63d0\u4f9b\u670d\u52a1\u7aef\u6743\u5a01\u7684\u6279\u91cf\u524d\u7f6e\u8d2d\u4e70\u3001\u7ea7\u8054\u9000\u8fd8\u548c\u6574\u9875\u91cd\u7f6e\u3002
