modLoader="javafml"
loaderVersion="[4,)"
license="GPL-3.0"

[[mixins]]
config="skill_respec_pill.mixins.json"

[[mods]]
modId="skill_respec_pill"
version="1.0.0"
displayName="技能后悔药"
authors="RinChan"
description='''
为 Puffish Skills 提供服务端权威的批量前置购买、级联退还和整页重置。
'''

[[dependencies.skill_respec_pill]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.skill_respec_pill]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.skill_respec_pill]]
modId="rinlib"
type="required"
versionRange="[1.0.0,2.0.0)"
ordering="AFTER"
side="BOTH" # mandatory-runtime

[[dependencies.skill_respec_pill]]
modId="puffish_skills"
type="required"
versionRange="[0.18.3,0.19.0)"
ordering="AFTER"
side="BOTH" # mandatory-runtime
