modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mixins]]
config="skill_respec_pill.mixins.json"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="rinlib"
type="required"
versionRange="[${rinlib_runtime_version}]"
ordering="AFTER"
side="BOTH" # mandatory-runtime

[[dependencies.${mod_id}]]
modId="puffish_skills"
type="required"
versionRange="[${puffish_skills_version}]"
ordering="AFTER"
side="BOTH" # mandatory-runtime
